"""empty message

Revision ID: 5727145069e3
Revises: d51357b49fa1
Create Date: 2022-09-22 00:56:33.796928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5727145069e3'
down_revision = 'd51357b49fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipos')
    # ### end Alembic commands ###
