"""empty message

Revision ID: b42b9e7b97f5
Revises: 5727145069e3
Create Date: 2022-09-22 01:06:18.477689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42b9e7b97f5'
down_revision = '5727145069e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadores', sa.Column('equipo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jugadores', 'equipos', ['equipo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jugadores', type_='foreignkey')
    op.drop_column('jugadores', 'equipo_id')
    # ### end Alembic commands ###
